parameters:
#    parameter_name: value

services:
    user.provider:
        class:     AppBundle\Service\UserAuthService
        arguments: [ "@service_container", "%auth_roles.frontend%" ]
    admin.provider:
        class:     AppBundle\Service\UserAuthService
        arguments: [ "@service_container", "%auth_roles.backend%" ]
